security:

    firewalls:
        backend:
            pattern:        ^/backend
            provider:       administradores
            http_basic:     ~
        extranet:
            pattern:        ^/extranet
            provider:       tiendas
            anonymous:      ~
            form_login:
                login_path: /extranet/login
                check_path: /extranet/login_check
            logout:
                path:       /extranet/logout
                target:     /extranet
                
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path:       usuario_logout
            remember_me:
                key: cupon1234
                lifetime: 3600
                
    access_control:
        - { path: ^/(es|en)/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/extranet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*, roles: ROLE_TIENDA }
        - { path: ^/backend/*, roles: ROLE_ADMIN }
        
    encoders:
        Cupon\UsuarioBundle\Entity\Usuario: plaintext
        Cupon\TiendaBundle\Entity\Tienda: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
            
        tiendas:
            entity: { class: Cupon\TiendaBundle\Entity\Tienda, property: login }
            
        administradores:
            memory:
                users:
                    # user = admin, pass = 1234
                    admin: { password: 1234, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_TIENDA, ROLE_USUARIO, ROLE_ALLOWED_TO_SWITCH]
    